DROP TABLE IF EXISTS points;
CREATE TABLE points(
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   speed INTEGER
);

DROP TABLE IF EXISTS races;
CREATE TABLE races(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT,
	type INTEGER NOT NULL
);

DROP TABLE IF EXISTS tracks;
CREATE TABLE tracks(
	id INTEGER PRIMARY KEY AUTOINCREMENT
);